---
- name: install nginx and start
  hosts: all
  become: root
  tasks:
  - name: install nginx webserver
    yum:
      name: git
      state: latest
  - name: start nginx
    service :
      name: nginx
      state: started
      enabled: yes
